INSERT INTO drivencook.pseudo (id, name, updated_at) VALUES (1, 'Poney orange', '2020-05-07 02:49:12');
INSERT INTO drivencook.pseudo (id, name, updated_at) VALUES (2, 'Souris épicée', '2020-07-05 01:03:53');
INSERT INTO drivencook.pseudo (id, name, updated_at) VALUES (4, 'Poulpe', null);
INSERT INTO drivencook.pseudo (id, name, updated_at) VALUES (5, 'Abeille des alpes2', '2020-07-05 02:59:54');
INSERT INTO drivencook.pseudo (id, name, updated_at) VALUES (6, 'Mangue', null);
INSERT INTO drivencook.pseudo (id, name, updated_at) VALUES (8, 'Yack des collines aa', '2020-07-05 01:02:55');
INSERT INTO drivencook.pseudo (id, name, updated_at) VALUES (14, 'Bulbe', null);
INSERT INTO drivencook.pseudo (id, name, updated_at) VALUES (15, 'Bambou', null);
INSERT INTO drivencook.pseudo (id, name, updated_at) VALUES (16, 'Piou', null);
INSERT INTO drivencook.pseudo (id, name, updated_at) VALUES (17, 'wouhou', null);