INSERT INTO drivencook.dish (id, name, category, description, diet, created_at, updated_at) VALUES (1, 'Frites', 'hot_dish', 'On est pas chez McDo en tout cas.', 'none', null, '2020-05-02 20:47:40');
INSERT INTO drivencook.dish (id, name, category, description, diet, created_at, updated_at) VALUES (3, 'Salade', 'cold_dish', 'Attention aux escargots !', 'vegan', null, null);
INSERT INTO drivencook.dish (id, name, category, description, diet, created_at, updated_at) VALUES (4, 'Coca', 'drink', 'C''est du coca sans le cola', 'vegan', null, '2020-05-13 12:02:11');
INSERT INTO drivencook.dish (id, name, category, description, diet, created_at, updated_at) VALUES (8, 'Coca3', 'drink', 'C''est pas le vrai mais...', 'none', null, '2020-05-04 13:49:19');
INSERT INTO drivencook.dish (id, name, category, description, diet, created_at, updated_at) VALUES (10, 'Coca1000', 'drink', 'C''est du coca mais 1000 fois mieux', 'none', null, null);
INSERT INTO drivencook.dish (id, name, category, description, diet, created_at, updated_at) VALUES (42, 'Coca Cola', 'drink', 'Rien que le vrai', 'vegetarian', null, '2020-05-12 21:48:20');
INSERT INTO drivencook.dish (id, name, category, description, diet, created_at, updated_at) VALUES (45, 'Lasagnes', 'hot_dish', 'Le bon plat de ta maman', 'none', '2020-05-12 22:15:37', '2020-05-12 22:29:48');
INSERT INTO drivencook.dish (id, name, category, description, diet, created_at, updated_at) VALUES (47, 'Test', 'hot_dish', 'Ceci n''est pas un plat', 'vegetarian', '2020-05-12 22:21:46', '2020-05-12 22:21:46');
INSERT INTO drivencook.dish (id, name, category, description, diet, created_at, updated_at) VALUES (48, 'Sprite', 'drink', 'De la limonade, mais en mieux.', 'vegetarian', '2020-05-12 22:30:17', '2020-05-12 22:30:17');
INSERT INTO drivencook.dish (id, name, category, description, diet, created_at, updated_at) VALUES (49, 'OrangeBleue22', 'salty_snack', 'OrangeBleue mais nouvelle version', 'vegan', null, '2020-07-05 00:52:31');
INSERT INTO drivencook.dish (id, name, category, description, diet, created_at, updated_at) VALUES (50, 'OrangeBleue1', 'cold_dish', 'OrangeBleue', 'none', null, null);
INSERT INTO drivencook.dish (id, name, category, description, diet, created_at, updated_at) VALUES (51, 'OrangeBleue2', 'cold_dish', 'OrangeBleue', 'none', null, null);
INSERT INTO drivencook.dish (id, name, category, description, diet, created_at, updated_at) VALUES (52, 'OrangeBleue3', 'cold_dish', 'OrangeBleue', 'none', null, null);
INSERT INTO drivencook.dish (id, name, category, description, diet, created_at, updated_at) VALUES (53, 'OrangeBleue4', 'cold_dish', 'OrangeBleue', 'none', null, null);
INSERT INTO drivencook.dish (id, name, category, description, diet, created_at, updated_at) VALUES (54, 'OrangeBleue5', 'cold_dish', 'OrangeBleue', 'none', null, null);
INSERT INTO drivencook.dish (id, name, category, description, diet, created_at, updated_at) VALUES (55, 'OrangeBleue6', 'cold_dish', 'OrangeBleue', 'none', null, null);
INSERT INTO drivencook.dish (id, name, category, description, diet, created_at, updated_at) VALUES (56, 'OrangeBleue7', 'cold_dish', 'OrangeBleue', 'none', null, null);
INSERT INTO drivencook.dish (id, name, category, description, diet, created_at, updated_at) VALUES (57, 'OrangeBleue8', 'cold_dish', 'OrangeBleue', 'none', null, null);
INSERT INTO drivencook.dish (id, name, category, description, diet, created_at, updated_at) VALUES (58, 'OrangeBleue9', 'cold_dish', 'OrangeBleue', 'none', null, null);
INSERT INTO drivencook.dish (id, name, category, description, diet, created_at, updated_at) VALUES (60, 'Bim boum', 'sweet_snack', 'Wouhou', 'none', '2020-07-05 00:52:54', '2020-07-05 00:52:54');
INSERT INTO drivencook.dish (id, name, category, description, diet, created_at, updated_at) VALUES (61, 'Miam', 'hot_dish', 'Miam miam', 'none', '2020-07-05 02:34:57', '2020-07-05 02:34:57');
INSERT INTO drivencook.dish (id, name, category, description, diet, created_at, updated_at) VALUES (62, 'plop', 'hot_dish', null, 'none', '2020-07-05 02:37:45', '2020-07-05 02:37:45');
INSERT INTO drivencook.dish (id, name, category, description, diet, created_at, updated_at) VALUES (64, 'bbbbC', 'cold_dish', null, 'none', '2020-07-05 02:38:47', '2020-07-05 02:40:13');
INSERT INTO drivencook.dish (id, name, category, description, diet, created_at, updated_at) VALUES (65, 'cc', 'salty_snack', null, 'vegan', '2020-07-05 02:39:21', '2020-07-05 02:39:21');