INSERT INTO drivencook.event (id, type, date_start, date_end, title, description, location_id, user_id, updated_at) VALUES (1, 'public', '2020-06-20', '2020-06-30', 'Publique', 'Nous le savons, Le Petit Larousse et Le Robert ont progressivement intégré un certain nombre de modifications issues de la « réforme » orthographique de 1990. Cependant, la graphie « évènement » n’est pas apparue en 1990. Elle a été admise par l’Académie française dès 1979, ce qui suppose un emploi bien antérieur, en particulier dans la littérature. La « réforme » orthographique de 1990 n’a fait qu’entériner une modification en usage depuis (au moins !) dix ans…

Mais revenons à nos dictionnaires dans lesquels on peut lire, à l’entrée événement : « événement ou évènement ». Comme le souligne malicieusement Bruno Dewaele, Le Robert n’a intégré « évènement » que dans l’édition de 2009, alors que Larousse cautionnait l’accent grave depuis plusieurs années déjà.

Quoi qu’il en soit, nos deux bibles de la langue française ne se mouillent pas : « évènement » est présenté comme variante orthographique d’événement. Le lecteur a donc le choix d’employer l’un ou l’autre… sans risquer de commettre une faute !', 1, 3, null);
INSERT INTO drivencook.event (id, type, date_start, date_end, title, description, location_id, user_id, updated_at) VALUES (6, 'private', '2020-07-10', '2020-07-10', 'Soutenance PA', 'Et ouais c''est bientôt déjà ...
:''-(', 47, 3, '2020-06-22 20:02:50');
INSERT INTO drivencook.event (id, type, date_start, date_end, title, description, location_id, user_id, updated_at) VALUES (7, 'news', '2020-06-22', '2020-06-24', 'news 1', 'Nous le savons, Le Petit Larousse et Le Robert ont progressivement intégré un certain nombre de modifications issues de la « réforme » orthographique de 1990. Cependant, la graphie « évènement » n’est pas apparue en 1990. Elle a été admise par l’Académie française dès 1979, ce qui suppose un emploi bien antérieur, en particulier dans la littérature. La « réforme » orthographique de 1990 n’a fait qu’entériner une modification en usage depuis (au moins !) dix ans…

Mais revenons à nos dictionnaires dans lesquels on peut lire, à l’entrée événement : « événement ou évènement ». Comme le souligne malicieusement Bruno Dewaele, Le Robert n’a intégré « évènement » que dans l’édition de 2009, alors que Larousse cautionnait l’accent grave depuis plusieurs années déjà.

Quoi qu’il en soit, nos deux bibles de la langue française ne se mouillent pas : « évènement » est présenté comme variante orthographique d’événement. Le lecteur a donc le choix d’employer l’un ou l’autre… sans risquer de commettre une faute !', 47, 3, null);
INSERT INTO drivencook.event (id, type, date_start, date_end, title, description, location_id, user_id, updated_at) VALUES (8, 'news', '2020-06-23', '2020-06-28', 'news 2', 'Nous le savons, Le Petit Larousse et Le Robert ont progressivement intégré un certain nombre de modifications issues de la « réforme » orthographique de 1990. Cependant, la graphie « évènement » n’est pas apparue en 1990. Elle a été admise par l’Académie française dès 1979, ce qui suppose un emploi bien antérieur, en particulier dans la littérature. La « réforme » orthographique de 1990 n’a fait qu’entériner une modification en usage depuis (au moins !) dix ans…

Mais revenons à nos dictionnaires dans lesquels on peut lire, à l’entrée événement : « événement ou évènement ». Comme le souligne malicieusement Bruno Dewaele, Le Robert n’a intégré « évènement » que dans l’édition de 2009, alors que Larousse cautionnait l’accent grave depuis plusieurs années déjà.

Quoi qu’il en soit, nos deux bibles de la langue française ne se mouillent pas : « évènement » est présenté comme variante orthographique d’événement. Le lecteur a donc le choix d’employer l’un ou l’autre… sans risquer de commettre une faute !', 4, 3, '2020-06-24 15:19:53');
INSERT INTO drivencook.event (id, type, date_start, date_end, title, description, location_id, user_id, updated_at) VALUES (9, 'private', '2020-07-05', '2020-07-05', 'Rendu PA3', 'Rendu du projet PA à cette date là :-''(', 47, 3, '2020-07-05 16:39:42');